export const books = [
  {
    slug: "hull",
    title: "Options, Futures, and Other Derivatives",
    shortTitle: "Hull",
    author: "John C. Hull",
    edition: "10th Edition",
    coverColor: "#1a4a8a",
    sortOrder: 1,
  },
  {
    slug: "rebonato",
    title: "Interest Rate Option Models",
    shortTitle: "Rebonato",
    author: "Riccardo Rebonato",
    edition: "2nd Edition",
    coverColor: "#2d6a4f",
    sortOrder: 2,
  },
  {
    slug: "tuckman",
    title: "Fixed Income Securities: Tools for Today's Markets",
    shortTitle: "Tuckman",
    author: "Bruce Tuckman & Angel Serrat",
    edition: "3rd Edition",
    coverColor: "#0f766e",
    sortOrder: 3,
  },
  {
    slug: "hull-risk",
    title: "Risk Management and Financial Institutions",
    shortTitle: "Hull Risk",
    author: "John C. Hull",
    edition: "5th Edition",
    coverColor: "#991b1b",
    sortOrder: 4,
  },
]
