// Flashcards keyed by chapter slug
// front = term/concept, back = definition/formula

export const flashcardsBySlug: Record<string, { front: string; back: string; tags: string[] }[]> = {
  "ch01-introduction": [
    { front: "Derivative", back: "A financial instrument whose value depends on (or is derived from) an underlying variable such as a stock price, commodity price, interest rate, or exchange rate.", tags: ["definition"] },
    { front: "Hedger", back: "A market participant who uses derivatives to reduce or eliminate an existing exposure to price risk.", tags: ["participants"] },
    { front: "Speculator", back: "A market participant who takes derivative positions to profit from anticipated price movements, accepting risk in doing so.", tags: ["participants"] },
    { front: "Arbitrageur", back: "A market participant who exploits price discrepancies across markets to earn riskless profits, driving prices toward equilibrium.", tags: ["participants"] },
    { front: "OTC vs Exchange-Traded", back: "OTC: bilaterally negotiated, customizable, counterparty credit risk.\nExchange: standardized, central clearing, no counterparty risk, margin required.", tags: ["markets"] },
    { front: "Long Position", back: "Agreement to buy an asset at a future date. Profits from rising prices. Maximum loss = initial price paid.", tags: ["positions"] },
    { front: "Short Position", back: "Agreement to sell an asset at a future date. Profits from falling prices. Theoretically unlimited loss.", tags: ["positions"] },
    { front: "Call Option Payoff", back: "max(S_T − K, 0)\nThe holder benefits when the stock price S_T exceeds the strike K.", tags: ["options", "payoff"] },
    { front: "Put Option Payoff", back: "max(K − S_T, 0)\nThe holder benefits when the stock price S_T falls below the strike K.", tags: ["options", "payoff"] },
    { front: "Clearinghouse", back: "Central counterparty that acts as buyer to every seller and seller to every buyer in exchange-traded markets, eliminating bilateral credit risk.", tags: ["exchange"] },
  ],
  "ch02-futures-markets": [
    { front: "Initial Margin", back: "A performance bond deposited when a futures position is opened. Typically 5–15% of contract value. Must be replenished on a margin call.", tags: ["margin"] },
    { front: "Maintenance Margin", back: "The minimum margin account balance. If balance falls below this level, a margin call is issued to restore to the initial margin.", tags: ["margin"] },
    { front: "Mark-to-Market (Daily Settlement)", back: "Daily adjustment of margin accounts based on the change in futures prices. Gains are credited; losses are debited. Eliminates credit risk accumulation.", tags: ["settlement"] },
    { front: "Open Interest", back: "The total number of outstanding long (or equivalently, short) futures contracts. Increases when new positions are opened; decreases when positions are closed.", tags: ["open-interest"] },
    { front: "Basis", back: "Basis = Spot price − Futures price. Converges to zero at expiry. Basis risk = uncertainty about the basis at hedge close-out.", tags: ["basis"] },
    { front: "Contango", back: "Market condition where futures price > spot price. Typical for assets with significant storage costs and no convenience yield.", tags: ["contango"] },
    { front: "Backwardation", back: "Market condition where futures price < spot price. Arises when convenience yield or dividends are large relative to cost of carry.", tags: ["backwardation"] },
    { front: "Convergence", back: "The property that futures price → spot price as expiry approaches. If they diverged at expiry, an arbitrage profit could be made via delivery.", tags: ["convergence"] },
  ],
  "ch03-hedging": [
    { front: "Optimal Hedge Ratio", back: "h* = ρ × (σ_S / σ_F)\nMinimizes variance of hedged position. ρ = correlation, σ_S = std dev of spot changes, σ_F = std dev of futures changes.", tags: ["hedge-ratio"] },
    { front: "Cross Hedge", back: "Hedging with a futures contract on a related but not identical asset. Hedge quality measured by R² of regression of spot on futures changes.", tags: ["cross-hedge"] },
    { front: "Hedge Effectiveness", back: "= ρ² (R-squared of regression). Represents the proportion of variance in spot returns explained by futures returns. Range: 0 to 1.", tags: ["hedge-effectiveness"] },
    { front: "Rolling Hedge", back: "When hedging horizon exceeds available futures maturities, close near-term futures and reopen with longer-dated contracts. Each roll introduces additional basis risk.", tags: ["rolling-hedge"] },
    { front: "Long Hedge", back: "Used when you will need to BUY an asset in the future. Buy futures now to lock in the purchase price. Example: airline buying jet fuel futures.", tags: ["long-hedge"] },
    { front: "Short Hedge", back: "Used when you currently own (or will produce) an asset. SELL futures to lock in the selling price. Example: a gold miner shorting gold futures.", tags: ["short-hedge"] },
    { front: "Portfolio Beta Hedge", back: "N = β × (Portfolio Value / Futures Value). To reduce β to β*: N = (β* − β) × P / F. Negative N means sell futures.", tags: ["portfolio-hedge", "beta"] },
  ],
  "ch04-interest-rates": [
    { front: "Continuous Compounding", back: "FV = PV × e^(rT). The limiting case of compounding frequency → ∞. Simplifies many formulas in derivatives pricing.", tags: ["compounding"] },
    { front: "Zero Rate (Spot Rate)", back: "The rate for an investment with a single payment at maturity (zero-coupon). Denoted r(T). Extracted via bootstrapping.", tags: ["zero-rate"] },
    { front: "Forward Rate", back: "R_F = (R₂T₂ − R₁T₁)/(T₂ − T₁)\nThe implied rate between two future dates, inferred from current zero rates.", tags: ["forward-rate"] },
    { front: "Duration (Macaulay)", back: "Weighted average time to receive cash flows, where weights = PV(cash flow) / Bond price. Measures interest rate sensitivity.", tags: ["duration"] },
    { front: "Modified Duration", back: "D* = D_Macaulay / (1 + y/m)\nΔP/P ≈ −D* × Δy\nThe percentage price change per unit change in yield.", tags: ["duration"] },
    { front: "DV01", back: "Dollar Value of a Basis Point = D* × P × 0.0001\nThe dollar change in bond price for a 1 basis point (0.01%) change in yield.", tags: ["dv01"] },
    { front: "Convexity", back: "ΔP/P ≈ −D*Δy + ½C(Δy)²\nSecond-order term capturing non-linearity of price-yield relationship. Always positive benefit.", tags: ["convexity"] },
    { front: "SOFR", back: "Secured Overnight Financing Rate. The USD risk-free benchmark (replaced LIBOR June 2023). Based on actual overnight Treasury repo transactions.", tags: ["sofr"] },
  ],
  "ch05-forward-futures-prices": [
    { front: "Cost of Carry Model (No Income)", back: "F₀ = S₀ × e^(rT)\nFor non-dividend-paying stocks. r = risk-free rate, T = time to delivery.", tags: ["cost-of-carry"] },
    { front: "Cost of Carry (Continuous Yield)", back: "F₀ = S₀ × e^((r−q)T)\nq = continuous dividend yield (or foreign interest rate for currencies).", tags: ["cost-of-carry"] },
    { front: "Covered Interest Rate Parity", back: "F₀ = S₀ × e^((r_d − r_f)T)\nLinks spot exchange rates, forward rates, and interest rate differentials.", tags: ["currency", "parity"] },
    { front: "Convenience Yield", back: "Benefit of holding a physical commodity (e.g., oil for immediate use). Reduces the futures price: F₀ = S₀ × e^((r+u−y)T).", tags: ["convenience-yield"] },
    { front: "Value of a Forward Contract", back: "f = (F₀ − K) × e^(−rT)\nValue to long position. Zero at inception (K = F₀); changes as the forward price F₀ moves.", tags: ["forward-value"] },
    { front: "Cash-and-Carry Arbitrage", back: "If F₀ > S₀e^(rT): borrow S₀, buy spot, sell forward at F₀. Profit = F₀ − S₀e^(rT). Forces F₀ ≤ S₀e^(rT).", tags: ["arbitrage"] },
  ],
  "ch07-swaps": [
    { front: "Plain Vanilla IRS", back: "One party pays fixed rate, other pays floating (SOFR). Notional not exchanged. Net payment = (fixed − floating) × notional × day fraction.", tags: ["swap"] },
    { front: "Swap as Bond Portfolio", back: "Value to fixed-rate payer = B_float − B_fixed.\nB_float = floating-rate bond ≈ par at reset dates.\nB_fixed = fixed coupon bond valued at current rates.", tags: ["swap-valuation"] },
    { front: "OIS Rate", back: "Overnight Index Swap rate. The rate on a swap where one leg pays compounded overnight rate (SOFR). Used to discount collateralized derivatives.", tags: ["ois"] },
    { front: "Currency Swap", back: "Exchange of principal AND interest in two different currencies. Principal exchanged at initiation and maturity. Used to create synthetic foreign-currency debt.", tags: ["currency-swap"] },
    { front: "Swap Rate at Inception", back: "The fixed rate that makes the swap value zero at inception. Determined by equating PV of fixed leg to PV of floating leg using forward rates.", tags: ["swap-rate"] },
    { front: "CVA", back: "Credit Valuation Adjustment: reduction in derivative value due to counterparty default risk. CVA = LGD × ∫ EE(t) × h(t) × D(t) dt.", tags: ["cva"] },
  ],
  "ch11-option-properties": [
    { front: "Put-Call Parity (European)", back: "c + K×e^(−rT) = p + S₀\nFor European options on non-dividend-paying stock. Derived from two portfolios with identical payoffs at expiry.", tags: ["put-call-parity"] },
    { front: "American Call Early Exercise", back: "An American call on a NON-DIVIDEND-PAYING stock should NEVER be exercised early. Selling is always better: alive option = intrinsic + time value > intrinsic alone.", tags: ["early-exercise"] },
    { front: "American Put Early Exercise", back: "Can be optimal to exercise an American put early when it is deep in the money. The interest on K earned if exercised can outweigh the time value and downside protection.", tags: ["early-exercise"] },
    { front: "Intrinsic Value", back: "Call: max(S − K, 0). Put: max(K − S, 0). The value if the option were exercised immediately. Option price ≥ intrinsic value always.", tags: ["intrinsic-value"] },
    { front: "European Call Lower Bound", back: "c ≥ max(S₀ − K×e^(−rT), 0). Tighter than the trivial bound c ≥ max(S₀−K, 0) when r > 0.", tags: ["lower-bound"] },
    { front: "Effect of Dividends on Options", back: "Dividends REDUCE call values (stock drops on ex-div date, reducing call payoff probability). Dividends INCREASE put values.", tags: ["dividends"] },
  ],
  "ch13-binomial-trees": [
    { front: "Risk-Neutral Probability (CRR)", back: "p = (e^(rΔt) − d) / (u − d)\nProbability of up-move under risk-neutral measure. Ensures stock earns risk-free rate.", tags: ["risk-neutral", "binomial"] },
    { front: "CRR Parameters", back: "u = e^(σ√Δt), d = 1/u = e^(−σ√Δt)\nConverges to GBM as Δt → 0. Ensures tree matches the true volatility σ.", tags: ["crr"] },
    { front: "Option Delta (Binomial)", back: "Δ = (f_u − f_d) / (Su − Sd)\nShares needed in the replicating portfolio. Identical to the delta in BSM.", tags: ["delta", "replication"] },
    { front: "American Option (Tree)", back: "At each node: f = max(Intrinsic value, e^(−rΔt)[p×f_u + (1−p)×f_d])\nEarly exercise if intrinsic > continuation value.", tags: ["american-option"] },
    { front: "Control Variate Technique", back: "Adjust American tree price: P_American ≈ P_American_tree + (P_European_BSM − P_European_tree). Removes systematic tree error.", tags: ["numerical-methods"] },
  ],
  "ch14-wiener-ito": [
    { front: "Wiener Process", back: "dz = ε√dt where ε~N(0,1). Properties: E[dz]=0, Var[dz]=dt, increments are independent. Also called standard Brownian motion.", tags: ["wiener-process"] },
    { front: "Geometric Brownian Motion", back: "dS = μS dt + σS dz\nS_T = S₀ × exp[(μ − σ²/2)T + σ√T × ε]\nStock prices are lognormally distributed.", tags: ["gbm"] },
    { front: "Itô's Lemma", back: "For G(S,t) with dS = a dt + b dz:\ndG = (∂G/∂t + ∂G/∂S·a + ½∂²G/∂S²·b²)dt + ∂G/∂S·b·dz\nThe ½∂²G/∂S²·b² term is the Itô correction.", tags: ["ito-lemma"] },
    { front: "Lognormal Distribution of S_T", back: "ln(S_T/S₀) ~ N[(μ−σ²/2)T, σ²T]\nThe mean of ln(S_T) = ln(S₀) + (μ−σ²/2)T\nThe mean of S_T = S₀ × e^(μT) (arithmetic)", tags: ["lognormal"] },
    { front: "Markov Property", back: "Future stock prices depend only on the current price, not the history. Consistent with weak-form market efficiency. GBM is a Markov process.", tags: ["markov"] },
  ],
  "ch15-black-scholes": [
    { front: "BSM Call Formula", back: "c = S₀N(d₁) − Ke^(−rT)N(d₂)\nd₁ = [ln(S₀/K) + (r + σ²/2)T] / (σ√T)\nd₂ = d₁ − σ√T", tags: ["bsm"] },
    { front: "BSM Put Formula", back: "p = Ke^(−rT)N(−d₂) − S₀N(−d₁)\nEquivalently: p = c − S₀ + Ke^(−rT) (put-call parity)", tags: ["bsm"] },
    { front: "N(d₁) Interpretation", back: "The delta of a European call. The hedge ratio: number of shares to hold per option sold to delta-hedge.", tags: ["bsm", "delta"] },
    { front: "N(d₂) Interpretation", back: "The risk-neutral probability that the call expires in-the-money: P^Q(S_T > K).", tags: ["bsm", "probability"] },
    { front: "BSM Assumptions", back: "1. GBM with constant σ\n2. No dividends\n3. No transaction costs\n4. Continuous trading\n5. Constant risk-free rate r\n6. No arbitrage", tags: ["bsm", "assumptions"] },
    { front: "Implied Volatility", back: "The value of σ that makes the BSM price equal the observed market price. Found numerically (no closed form). Represents market's consensus view of future vol.", tags: ["implied-volatility"] },
    { front: "BSM with Dividends (Merton)", back: "c = S₀e^(−qT)N(d₁) − Ke^(−rT)N(d₂)\nReplace S₀ with S₀e^(−qT) where q = continuous dividend yield.", tags: ["bsm", "dividends"] },
  ],
  "ch19-greeks": [
    { front: "Delta (Δ)", back: "Δ = ∂V/∂S. Call delta ∈ (0,1); Put delta ∈ (−1,0). For BSM call: Δ = N(d₁).", tags: ["greeks", "delta"] },
    { front: "Gamma (Γ)", back: "Γ = ∂²V/∂S² = ∂Δ/∂S. Highest for ATM options near expiry. All long options have Γ > 0.", tags: ["greeks", "gamma"] },
    { front: "Theta (Θ)", back: "Θ = ∂V/∂t. Usually negative for long options (time decay). BSM PDE: Θ + rSΔ + ½σ²S²Γ = rV.", tags: ["greeks", "theta"] },
    { front: "Vega (ν)", back: "ν = ∂V/∂σ. Positive for all long options. Highest for ATM options with long time to expiry.", tags: ["greeks", "vega"] },
    { front: "Rho (ρ)", back: "ρ = ∂V/∂r. Calls: ρ > 0 (higher rates → higher call value). Puts: ρ < 0.", tags: ["greeks", "rho"] },
    { front: "Theta-Gamma Relationship", back: "For a delta-neutral portfolio: Θ + ½σ²S²Γ ≈ 0. Long gamma costs theta; short gamma earns theta. They are the price of each other.", tags: ["theta-gamma"] },
    { front: "Delta-Neutral Portfolio", back: "A portfolio with Δ_total = 0. Insensitive to small stock price moves. Requires rebalancing as S changes (due to non-zero gamma).", tags: ["delta-neutral"] },
  ],
  "ch20-volatility-smiles": [
    { front: "Volatility Smile", back: "A plot of implied volatility vs. strike. If BSM were correct, it would be flat. Real smiles reveal the market's risk-neutral distribution deviates from lognormal.", tags: ["volatility-smile"] },
    { front: "Equity Volatility Skew", back: "Lower strikes → higher IV (negative skew). OTM puts are expensive. Reflects market fear of crashes: the risk-neutral distribution has a heavy left tail.", tags: ["equity-skew"] },
    { front: "Currency Volatility Smile", back: "Symmetric smile: higher IV for both OTM calls and OTM puts. Both extreme appreciations and depreciations are more likely than lognormal.", tags: ["currency-smile"] },
    { front: "Heston Model", back: "Stochastic volatility model: dS = rS dt + √v S dz_S; dv = κ(θ−v)dt + ξ√v dz_v. Correlated Brownian motions. Generates realistic vol smiles.", tags: ["heston"] },
    { front: "Local Volatility (Dupire)", back: "σ(S,t) is a deterministic function calibrated to exactly reproduce all observed option prices. Dupire's formula: σ²_local = (∂C/∂T + ...) / (½K²∂²C/∂K²).", tags: ["local-vol"] },
    { front: "Breeden-Litzenberger", back: "Risk-neutral PDF: g(K,T) = e^(rT) × ∂²C/∂K². The second derivative of call prices with respect to strike gives the implied risk-neutral density.", tags: ["risk-neutral-density"] },
  ],
  "ch22-value-at-risk": [
    { front: "Value at Risk (VaR)", back: "VaR_α = the loss amount such that P(Loss > VaR) = 1−α. E.g., 99% 1-day VaR of $1M = 1% chance of losing more than $1M in one day.", tags: ["var"] },
    { front: "Expected Shortfall (ES/CVaR)", back: "ES_α = E[Loss | Loss > VaR_α]. The expected loss in the tail. Always ≥ VaR. A coherent risk measure (satisfies subadditivity). Required under Basel FRTB.", tags: ["es", "cvar"] },
    { front: "Square Root of Time Rule", back: "N-day VaR ≈ √N × 1-day VaR. Assumes i.i.d. daily returns. Used for scaling under the variance-covariance approach.", tags: ["var", "scaling"] },
    { front: "Historical Simulation VaR", back: "Apply last N days of actual returns to today's portfolio. Percentile of resulting P&L distribution = VaR. Captures fat tails but backward-looking.", tags: ["var", "historical-simulation"] },
    { front: "VaR Coherence Problem", back: "VaR is NOT subadditive: VaR(A+B) can exceed VaR(A)+VaR(B) for non-normal distributions. Expected shortfall (ES) is subadditive and therefore coherent.", tags: ["var", "coherence"] },
  ],
  // Rebonato flashcards
  "rch01-framework": [
    { front: "T-Forward Measure", back: "Measure using P(t,T) (zero-coupon bond maturing at T) as numeraire. Under this measure, the T-forward price of any asset is a martingale.", tags: ["forward-measure"] },
    { front: "Annuity Measure (Swap Measure)", back: "Measure using annuity A(t) = Σ τᵢP(t,Tᵢ) as numeraire. The forward swap rate is a martingale under this measure, giving Black's formula for swaptions.", tags: ["swap-measure"] },
    { front: "Why IR Modelling Is Different", back: "1. Mean reversion required\n2. Entire yield curve must be modelled consistently\n3. No single 'underlying'—all maturities evolve jointly\n4. Must fit observed yield curve", tags: ["framework"] },
    { front: "Short Rate r(t)", back: "Instantaneous borrowing rate: P(t,T) = E^Q[exp(−∫_t^T r(s)ds)]. A mathematical abstraction; not directly observed. SOFR overnight rate is the closest proxy.", tags: ["short-rate"] },
  ],
  "rch06-hjm": [
    { front: "HJM Drift Restriction", back: "μ(t,T) = σ(t,T) × ∫_t^T σ(t,s)ds\nOnce volatility σ(t,T) is specified, the no-arbitrage drift is fully determined. Key result: volatility drives everything.", tags: ["hjm"] },
    { front: "HJM Forward Rate Dynamics", back: "df(t,T) = μ(t,T)dt + σ(t,T)dz\nModels the entire forward rate curve. Short-rate models are special cases with specific σ(t,T) forms.", tags: ["hjm"] },
    { front: "HJM Markovian Special Case", back: "For σ(t,T) = σe^(−a(T−t)), HJM reduces to Hull-White. The exponential form ensures the future state depends only on the current state (Markovian).", tags: ["hjm", "markovian"] },
  ],
  "rch07-lmm-intro": [
    { front: "LMM / BGM Model", back: "The LIBOR Market Model (Brace-Gatarek-Musiela, 1997): models forward LIBOR rates directly. Each rate Lₖ has lognormal dynamics under its forward measure, giving Black's formula for caplets.", tags: ["lmm"] },
    { front: "Caplet Pricing (LMM)", back: "Caplet = τₖ × P(0,Tₖ₊₁) × [Lₖ(0)N(d₁) − KN(d₂)]\nd₁ = [ln(Lₖ(0)/K) + ½v²Tₖ]/(v√Tₖ), v² = avg squared vol\nExactly Black's formula.", tags: ["lmm", "black-formula"] },
    { front: "Cap = Sum of Caplets", back: "A cap is decomposed into a series of caplets, each reset at a different date. Cap price = Σ Capletₖ. LMM prices each caplet by Black's formula.", tags: ["lmm", "cap"] },
  ],
  "rch08-lmm-dynamics": [
    { front: "Rebonato Humped Vol", back: "σₖ(t) = [a + b(Tₖ−t)]exp[−c(Tₖ−t)] + d\nProduces a hump in vol: rises then decays. Matches observed cap vol structures.", tags: ["lmm", "vol-parameterization"] },
    { front: "Rebonato Correlation", back: "ρᵢⱼ = exp[−β|Tᵢ−Tⱼ|]\nOne parameter β controls correlation decay. Small β → all rates nearly perfectly correlated; large β → only adjacent rates correlated.", tags: ["lmm", "correlation"] },
    { front: "Rank-Reduction (PCA)", back: "Replace full n×n correlation matrix with r-factor approximation via PCA. r=3 factors capture: parallel shift (80%), slope (15%), curvature (5%) of yield curve moves.", tags: ["pca", "rank-reduction"] },
  ],
  "rch10-smile-models": [
    { front: "SABR Model", back: "dF = σF^β dW, dσ = ασ dZ, corr(dW,dZ)=ρ dt\nFour params: α (vol of vol), β (elasticity), ρ (skew), σ₀ (initial vol).\nIndustry standard for IR smile.", tags: ["sabr"] },
    { front: "SABR β Parameter", back: "β=0: normal (Bachelier) dynamics; β=0.5: CEV; β=1: lognormal. β<1 with rates near zero reduces explosion risk. β=0 preferred when rates can be negative.", tags: ["sabr", "beta"] },
    { front: "SABR ρ Parameter", back: "ρ<0: negative correlation → negative skew (lower strikes have higher IV). Typical for interest rates. ρ>0 gives positive skew.", tags: ["sabr", "skew"] },
    { front: "Displaced Diffusion", back: "dL = σ(L+δ)dz. Rates can be as negative as −δ. Simple extension of lognormal LMM that handles near-zero/negative rates.", tags: ["displaced-diffusion"] },
  ],
  "rch13-model-risk": [
    { front: "Model Risk", back: "Risk of loss due to errors in the models used for pricing and risk management. Two sources: wrong model structure, or correct model incorrectly implemented.", tags: ["model-risk"] },
    { front: "Calibration Instability", back: "Day-to-day jumps in model parameters due to small market moves. Generates 'phantom P&L' from parameter changes rather than actual market moves. Reduced by regularization.", tags: ["calibration-instability"] },
    { front: "Model P&L vs Market P&L", back: "Model P&L = P&L from parameter changes during recalibration (a hedging artifact). Market P&L = true gains/losses from market moves. Good risk management separates these.", tags: ["model-risk"] },
  ],
}
