// Tuckman & Serrat "Fixed Income Securities" — questions by chapter slug

const base = { isActive: true, tags: "[]", sourceRef: null }

const tuckmanCh01: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "The discount factor d(t) represents the present value of:",
    explanation: "d(t) is defined as the current price of a zero-coupon bond paying exactly $1 at time t. All bond pricing flows from these discount factors.",
    answerData: JSON.stringify({ choices: ["$1 received today", "$1 received at time t", "The annual coupon of a par bond", "The par swap rate at maturity t"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "Bootstrapping discount factors from bond prices works by:",
    explanation: "Bootstrapping extracts discount factors sequentially: the shortest maturity bond gives d(t1), then using that to isolate d(t2) from the next bond, and so on. It requires no-arbitrage to hold.",
    answerData: JSON.stringify({ choices: ["Regressing bond prices on duration", "Sequentially solving for discount factors from observed bond prices, shortest maturity first", "Averaging yields across the curve", "Fitting a parametric model to all maturities simultaneously"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "EASY",
    stem: "Under no-arbitrage, two portfolios with identical future cash flows in all scenarios must have the same price today.",
    explanation: "This is the law of one price — the foundational principle of derivative pricing. Any price difference would allow a riskless profit, which the market rapidly arbitrages away.",
    answerData: JSON.stringify({ correct: true }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "If a 2-year zero-coupon bond has a price of 92.46 per 100 face value, what is d(2)?",
    explanation: "The discount factor is simply the bond price expressed as a fraction of face value: d(2) = 92.46/100 = 0.9246. This is the PV of $1 received in 2 years.",
    answerData: JSON.stringify({ choices: ["0.0754", "0.9246", "1.0820", "7.54%"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "Replication pricing of a derivative means:",
    explanation: "Replication builds a portfolio of traded instruments that exactly matches the derivative's cash flows. The derivative price must equal the replicating portfolio cost — otherwise arbitrage exists. No assumptions about investor preferences are needed.",
    answerData: JSON.stringify({ choices: ["Using historical data to forecast derivative prices", "Constructing a portfolio of traded instruments that mimics the derivative's cash flows exactly", "Applying a risk premium to the risk-free rate", "Optimizing the portfolio to minimize tracking error"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "Discount factors must always be greater than 1 when interest rates are positive.",
    explanation: "False. Discount factors are LESS than 1 when interest rates are positive — a dollar today is worth more than a dollar in the future, so the PV of $1 received later is below $1.",
    answerData: JSON.stringify({ correct: false }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "A bond pays coupons of $5 at t=0.5 and $105 at t=1. If d(0.5)=0.9756 and d(1)=0.9524, what is the bond price?",
    explanation: "Price = 5×d(0.5) + 105×d(1) = 5×0.9756 + 105×0.9524 = 4.878 + 100.002 = 104.88. This is direct application of the discount factor pricing formula.",
    answerData: JSON.stringify({ choices: ["100.00", "102.44", "104.88", "107.50"], correctIndex: 2 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "Which of the following is NOT a valid property of discount factors under positive interest rates?",
    explanation: "Discount factors are always positive, always less than 1 (for t>0), and strictly decreasing in t (longer-dated dollars are worth less today). They are NOT necessarily linear in t.",
    answerData: JSON.stringify({ choices: ["d(0) = 1", "0 < d(t) < 1 for t > 0", "d(t1) > d(t2) when t1 < t2", "d(t) is a linear function of t"], correctIndex: 3 }),
  },
]

const tuckmanCh02: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "The spot rate s(2) is best described as:",
    explanation: "The spot rate (or zero rate) for maturity T is the yield on a zero-coupon bond maturing at T. It is not contaminated by reinvestment assumptions because there are no intermediate cash flows.",
    answerData: JSON.stringify({ choices: ["The coupon rate on a 2-year par bond", "The yield on a 2-year zero-coupon bond", "The forward rate from year 1 to year 2", "The swap rate on a 2-year swap"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "EASY",
    stem: "When the yield curve is upward-sloping, forward rates lie above spot rates.",
    explanation: "True. Forward rates are the marginal rates of return for the last increment of time. When the curve is upward-sloping (future rates higher), the forward rate at each maturity exceeds the spot rate to that maturity — a 'pull-up' effect.",
    answerData: JSON.stringify({ correct: true }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "The par rate y(T) is defined as the coupon rate that:",
    explanation: "The par rate is the coupon rate that prices a bond exactly at par (face value = 100). It is the standard convention for quoting interest rate swap rates in the market.",
    answerData: JSON.stringify({ choices: ["Maximizes a bond's duration", "Makes a bond's price equal to its face value", "Equals the 1-year forward rate at maturity T", "Minimizes interest rate risk"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "The 1-year spot rate is 4% and the 2-year spot rate is 5% (continuous compounding). What is the 1-year forward rate one year from now?",
    explanation: "Under continuous compounding: f(1,2) = s(2)×2 − s(1)×1 = 5%×2 − 4%×1 = 10% − 4% = 6%. Forward rates are computed as the marginal return for extending maturity.",
    answerData: JSON.stringify({ choices: ["4.5%", "5.0%", "6.0%", "4.0%"], correctIndex: 2 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "When the yield curve is inverted, which of the following correctly describes the relationship between spot and forward rates?",
    explanation: "When the curve is inverted (long rates below short rates), forward rates lie BELOW spot rates. The forward rate is the marginal rate; if spot rates decline with maturity, the forward rate must be below the spot to pull the average down.",
    answerData: JSON.stringify({ choices: ["Forward rates equal spot rates at every maturity", "Forward rates lie above spot rates", "Forward rates lie below spot rates", "Forward rates are undefined when the curve is inverted"], correctIndex: 2 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "Spot rates, forward rates, and par rates all contain the same information about the yield curve — given one, you can derive the other two.",
    explanation: "True. They are three equivalent representations of the same discount curve. The choice between them is a matter of convention and application, not information content.",
    answerData: JSON.stringify({ correct: true }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "For which application are par rates most naturally suited?",
    explanation: "Par rates are the standard market convention for quoting swap rates. A par swap rate is defined as the fixed rate that makes a swap's value zero at inception — exactly analogous to a par bond's coupon rate.",
    answerData: JSON.stringify({ choices: ["Pricing zero-coupon bonds", "Bootstrapping discount factors", "Quoting and comparing interest rate swaps", "Computing DV01 for a bond portfolio"], correctIndex: 2 }),
  },
]

const tuckmanCh03: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "DV01 measures:",
    explanation: "DV01 (Dollar Value of 01, or PVBP) is the dollar change in a bond's price for a 1 basis point (0.01%) decrease in yield. It is the most direct measure of interest rate exposure in fixed income.",
    answerData: JSON.stringify({ choices: ["The percentage price change per 100bp yield move", "The dollar price change for a 1bp decrease in yield", "The average time to receive a bond's cash flows", "The second derivative of price with respect to yield"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "Which bond has the longest Macaulay duration?",
    explanation: "A zero-coupon bond has Macaulay duration exactly equal to its maturity — all cash flow is at maturity. Coupon bonds receive cash flows before maturity, reducing weighted average time. So a 30-year zero has the longest duration among standard bonds.",
    answerData: JSON.stringify({ choices: ["A 5-year 8% coupon bond", "A 10-year floating-rate bond", "A 30-year zero-coupon bond", "A 2-year Treasury"], correctIndex: 2 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "A callable bond typically exhibits negative convexity at low yield levels.",
    explanation: "True. When yields fall, the issuer is more likely to call the bond. This caps the price appreciation (the call option is exercised, limiting the upside), producing negative convexity — the price rises less than expected as yields decline.",
    answerData: JSON.stringify({ correct: true }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "A portfolio has modified duration of 5 and market value of $10 million. What is its approximate DV01?",
    explanation: "DV01 = D_mod × P × 0.0001 = 5 × $10,000,000 × 0.0001 = $5,000. This means a 1bp yield decline gains approximately $5,000.",
    answerData: JSON.stringify({ choices: ["$500", "$5,000", "$50,000", "$500,000"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "Modified duration differs from Macaulay duration in that it:",
    explanation: "Modified duration adjusts Macaulay duration for the compounding frequency: D_mod = D_mac / (1 + y/m). It directly gives percentage price sensitivity, while Macaulay duration is a weighted average time measure.",
    answerData: JSON.stringify({ choices: ["Is measured in years squared", "Is adjusted for the compounding frequency to give percentage price sensitivity", "Only applies to zero-coupon bonds", "Ignores the timing of coupon payments"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "Convexity adjustment improves the duration approximation because:",
    explanation: "The price-yield relationship is curved (convex for standard bonds), not linear. Duration captures the slope (first derivative). Convexity captures the curvature (second derivative). For large yield moves, the convexity term is significant and must be included for accurate P&L attribution.",
    answerData: JSON.stringify({ choices: ["It incorporates credit risk into the price estimate", "It captures the curvature of the price-yield relationship, improving accuracy for large yield moves", "It adjusts for the difference between coupon and zero-coupon bonds", "It accounts for the embedded optionality in all bonds"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "EASY",
    stem: "For a non-callable bond, higher convexity is always beneficial to the bondholder.",
    explanation: "True. For non-callable bonds, convexity is always positive and always works in the investor's favour: prices rise more than duration predicts when yields fall, and fall less than duration predicts when yields rise.",
    answerData: JSON.stringify({ correct: true }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "Two bonds have equal modified duration of 7 years but bond A has convexity of 80 and bond B has convexity of 40. If yields move ±200bp, which bond performs better?",
    explanation: "Higher convexity benefits the bondholder for large moves in either direction: the bond rises more when rates fall and falls less when rates rise. Bond A, with double the convexity, will outperform bond B for any large parallel yield shift.",
    answerData: JSON.stringify({ choices: ["Bond A performs better if rates fall, Bond B if rates rise", "Bond B performs better in both scenarios due to lower convexity risk", "Bond A performs better in both scenarios (up or down rate moves)", "Performance is identical since durations are equal"], correctIndex: 2 }),
  },
]

const tuckmanCh04: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "In a plain vanilla interest rate swap, the party paying fixed is said to be:",
    explanation: "The fixed-rate payer gains when rates rise (floating leg receipts increase above the fixed payment) — analogous to being short a fixed-rate bond and long a floating-rate bond. By market convention this is 'long the swap'.",
    answerData: JSON.stringify({ choices: ["Short the swap", "Long the swap", "Neutral on interest rates", "The protection seller"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "A floating-rate bond resets its coupon to the market rate at each payment date. On a reset date, the floating-rate bond's price equals:",
    explanation: "On a reset date, the floating-rate bond's next coupon is set equal to the current market rate. Its subsequent cash flows (coupon + principal) are worth exactly par when discounted at the prevailing rate. Hence price = par.",
    answerData: JSON.stringify({ choices: ["Its duration-adjusted fair value", "Par (face value)", "The present value of all future LIBOR settings", "Zero, as there is no embedded option"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "The par swap rate is the fixed rate that:",
    explanation: "The par swap rate is set so the swap has zero NPV at inception — neither party pays a premium. It is equivalent to the par rate from the discount curve, reflecting the current level of interest rates.",
    answerData: JSON.stringify({ choices: ["Maximizes the fixed payer's profit", "Makes the initial value of the swap equal to zero", "Equals the 10-year Treasury yield", "Minimizes the floating payer's funding cost"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "A swap can be valued as the difference between a fixed-rate bond and a floating-rate bond.",
    explanation: "True. A pay-fixed swap = short fixed bond + long floating bond. Since floating-rate bonds price at par on reset dates, the swap value equals par minus the value of the fixed-rate bond (for receive-fixed) or vice versa.",
    answerData: JSON.stringify({ correct: true }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "A Forward Rate Agreement (FRA) is best described as:",
    explanation: "A FRA is a single-payment OTC contract where one party pays a fixed rate and receives a floating rate (or vice versa) at a future date on a notional. It is a one-period swap and is the building block of multi-period swaps.",
    answerData: JSON.stringify({ choices: ["A long-dated currency forward", "A single-period swap settling at a future date on a notional amount", "An option to enter a swap", "A bond with a variable coupon"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "The net payment on a $100M pay-fixed swap when the fixed rate is 3% and 6-month LIBOR is 4% (semi-annual, ACT/360, 182 days) is approximately:",
    explanation: "The floating payment = 4% × 182/360 × $100M ≈ $2.022M. The fixed payment = 3% × 182/360 × $100M ≈ $1.517M. Net received by the fixed payer = $2.022M − $1.517M ≈ $0.506M. When floating > fixed, the fixed payer receives the net.",
    answerData: JSON.stringify({ choices: ["Pay $0.506M (net loss for fixed payer)", "Receive $0.506M (net gain for fixed payer)", "Pay $3.539M net", "Zero — swap payments are always equal"], correctIndex: 1 }),
  },
]

const tuckmanCh05: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "Prepayment risk in mortgage-backed securities refers to:",
    explanation: "Prepayment risk arises because mortgagors can repay principal early. This is most damaging to investors when rates fall (refinancing wave), forcing reinvestment at lower rates — contraction risk. It also creates extension risk when rates rise.",
    answerData: JSON.stringify({ choices: ["The risk that the mortgage servicer defaults", "The risk of early principal repayment, typically accelerating when rates fall", "The risk of rising credit losses on the underlying mortgages", "The risk of falling house prices reducing collateral value"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "Mortgage-backed securities (pass-throughs) typically exhibit negative convexity.",
    explanation: "True. When rates fall, prepayments accelerate (borrowers refinance) — limiting price appreciation. When rates rise, prepayments slow — extending the bond's life and amplifying losses. Both effects reduce convexity below zero.",
    answerData: JSON.stringify({ correct: true }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "Option-Adjusted Spread (OAS) is designed to:",
    explanation: "OAS removes the value of the embedded prepayment option from the bond's spread, leaving the pure credit and liquidity spread. This allows fair comparison between MBS with different prepayment characteristics and between MBS and option-free bonds.",
    answerData: JSON.stringify({ choices: ["Add the value of the prepayment option to yield spreads", "Measure the spread after stripping out the embedded option value, enabling fair comparisons", "Express MBS duration in option-adjusted terms", "Compute the weighted-average coupon of the mortgage pool"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "In a CMO sequential-pay structure, which tranche benefits most from slow prepayments?",
    explanation: "In a sequential-pay CMO, the Z-tranche (accrual bond) receives no cash until all prior tranches are retired. Slow prepayments delay that point but allow the Z-tranche to accrue interest at a compound rate — so Z-tranche investors actually benefit from slower prepayments (extension).",
    answerData: JSON.stringify({ choices: ["The A (shortest) tranche, which gets paid first", "The B tranche, which acts as a buffer", "The Z (accrual) tranche, which accrues interest until prior tranches are paid off", "All tranches equally"], correctIndex: 2 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "Contraction risk in MBS refers to:",
    explanation: "Contraction risk is one face of prepayment risk: when rates fall, borrowers refinance, returning principal early. Investors must then reinvest at the now-lower prevailing rates — they lose the above-market coupons they expected to receive.",
    answerData: JSON.stringify({ choices: ["The risk that bond duration extends when rates rise", "The risk of receiving principal back early when rates fall, forcing reinvestment at lower rates", "The risk that the MBS pool shrinks due to defaults", "The risk that the CMO structure collapses"], correctIndex: 1 }),
  },
]

const tuckmanCh06: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "In the Vasicek model, interest rates are modeled as:",
    explanation: "The Vasicek model specifies: dr = a(b − r)dt + σdW. Rates mean-revert toward b at speed a, with constant volatility σ. The key limitation is that rates can go negative, which is theoretically problematic but sometimes observed empirically.",
    answerData: JSON.stringify({ choices: ["A random walk with no drift", "A mean-reverting process with constant volatility", "A geometric Brownian motion like equities", "A jump-diffusion process with Poisson arrivals"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "The key advantage of the Hull-White model over Vasicek is that it:",
    explanation: "Hull-White adds a time-dependent drift θ(t) to the Vasicek framework, specifically calibrated to match the current observed term structure. This makes it a no-arbitrage model: it is consistent with today's prices by construction.",
    answerData: JSON.stringify({ choices: ["Produces log-normal interest rates that cannot go negative", "Is calibrated to match the current observed yield curve exactly", "Has a closed-form solution for option prices at all strikes", "Eliminates mean reversion for computational simplicity"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "Equilibrium term structure models are calibrated to match today's observed yield curve exactly.",
    explanation: "False. Equilibrium models (Vasicek, CIR) are built from economic assumptions about preferences and production — they produce a theoretical yield curve that may not match the market exactly. No-arbitrage models (Hull-White, Ho-Lee) are specifically designed to fit the current curve.",
    answerData: JSON.stringify({ correct: false }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "The CIR model differs from Vasicek primarily in that it:",
    explanation: "In the CIR model, volatility is proportional to √r, which means volatility falls toward zero as rates approach zero. This prevents negative interest rates — a significant theoretical advantage over Vasicek's constant volatility.",
    answerData: JSON.stringify({ choices: ["Has no mean reversion", "Uses volatility proportional to √r, preventing negative interest rates", "Is a multi-factor model", "Assumes a flat yield curve at all times"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "A one-factor short-rate model implies that all bond yields are driven by a single source of uncertainty. The main practical limitation of this is:",
    explanation: "With a single factor, all yields move together perfectly — changes in the 2-year rate and the 30-year rate are perfectly correlated. In reality, the yield curve can change shape (steepen/flatten/butterfly), requiring at least 2–3 factors to capture slope and curvature movements.",
    answerData: JSON.stringify({ choices: ["One-factor models cannot be used for option pricing", "All yield curve moves are perfectly correlated, failing to capture slope and curvature changes", "One-factor models always produce upward-sloping yield curves", "The single factor must be observable in the market"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "Under risk-neutral pricing, a zero-coupon bond price P(t,T) equals:",
    explanation: "Under the risk-neutral measure Q, the no-arbitrage price of any security is the discounted expectation of its payoff. For a zero-coupon bond paying $1 at T, P(t,T) = E^Q[exp(−∫ᵗᵀ rₛ ds)]. This is the key equation linking short-rate models to bond prices.",
    answerData: JSON.stringify({ choices: ["The expected short rate times (T−t)", "The risk-neutral expectation of e^(−∫ rₛ ds) from t to T", "The real-world probability of no default times the face value", "The forward rate integrated from t to T"], correctIndex: 1 }),
  },
]

export const tuckmanQuestionsBySlug: Record<string, typeof tuckmanCh01> = {
  "ch01-discount-factors": tuckmanCh01,
  "ch02-spot-forward-rates": tuckmanCh02,
  "ch03-duration-convexity": tuckmanCh03,
  "ch04-swaps": tuckmanCh04,
  "ch05-mortgages-mbs": tuckmanCh05,
  "ch06-term-structure-models": tuckmanCh06,
}
