// Damodaran "Investment Valuation" — questions by chapter slug

const base = { isActive: true, tags: "[]", sourceRef: null }

const damCh01: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "Which of the following is NOT one of Damodaran's three broad approaches to valuation?",
    explanation: "Damodaran's three approaches are: (1) Intrinsic/DCF valuation, (2) Relative valuation using multiples, and (3) Contingent claim (options) valuation. 'Accounting valuation' based on book value is not one of the three — book value appears within relative valuation (P/B) but is not a standalone approach.",
    answerData: JSON.stringify({ choices: ["Discounted cash flow (intrinsic) valuation", "Relative valuation using multiples", "Accounting book-value valuation", "Contingent claim (options) valuation"], correctIndex: 2 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "EASY",
    stem: "According to Damodaran, uncertainty in future cash flows is a reason to avoid DCF valuation.",
    explanation: "False. Damodaran argues that uncertainty is inherent in valuation and cannot be eliminated. The goal is to be explicit about assumptions and quantify uncertainty through scenarios and sensitivity analysis — not to abandon DCF because the future is uncertain.",
    answerData: JSON.stringify({ correct: false }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "Damodaran argues that a good valuation requires both a narrative and a model because:",
    explanation: "A narrative without numbers can be wishful thinking; numbers without a story can be meaningless. The narrative defines the business assumptions (market size, margins, competitive position) and the model translates them into cash flows. Each must be consistent with the other.",
    answerData: JSON.stringify({ choices: ["Regulators require both for disclosure", "The narrative defines the business assumptions that the numbers must reflect — each constrains the other", "Models alone cannot produce a discount rate", "Narratives are required for relative valuation but models for DCF"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "An analyst 'reverse engineers' a DCF by starting with the current stock price and solving for the growth rate that justifies it. This is useful because:",
    explanation: "Reverse-engineering shows the implied assumptions already in the market price. Rather than asking 'what is the stock worth?' you ask 'what does the market already believe?' This makes the investment decision cleaner: do you agree or disagree with those embedded assumptions?",
    answerData: JSON.stringify({ choices: ["It eliminates the need to estimate the discount rate", "It reveals the growth rate embedded in the market price, clarifying what you must believe to buy or sell", "It is more accurate than a standard DCF", "It bypasses the terminal value calculation"], correctIndex: 1 }) },
]

const damCh02: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "FCFF (Free Cash Flow to the Firm) should be discounted at:",
    explanation: "FCFF represents cash available to all capital providers (equity and debt holders). The appropriate discount rate must reflect the blended cost of all capital — hence the WACC. Discounting FCFF at the cost of equity alone would give too high a value (underestimating the discount rate).",
    answerData: JSON.stringify({ choices: ["The cost of equity only", "The cost of debt only", "The weighted average cost of capital (WACC)", "The risk-free rate"], correctIndex: 2 }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "In a DCF, the terminal value (Gordon Growth Model) is computed as:",
    explanation: "Terminal value = FCF_{n+1} / (WACC − g), where g is the stable long-run growth rate. This is the Gordon Growth Model applied to the terminal year cash flow. The formula assumes the firm grows at a constant rate g forever after the explicit forecast period.",
    answerData: JSON.stringify({ choices: ["FCF_n × (1+g)", "FCF_{n+1} / (WACC − g)", "FCF_n / WACC", "EBITDA_n × exit multiple"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "MEDIUM",
    stem: "A firm's terminal growth rate can sustainably exceed the long-run nominal GDP growth rate of the economy.",
    explanation: "False. If a firm's terminal growth rate exceeded nominal GDP growth forever, the firm would eventually become larger than the entire economy — which is impossible. Terminal growth rates for most firms should be set at or below nominal GDP growth (typically 2–4% for developed markets).",
    answerData: JSON.stringify({ correct: false }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "Which component of the DCF typically represents the largest share of total firm value for a high-growth company?",
    explanation: "For high-growth firms (e.g., tech companies), the terminal value can represent 70–85% of total DCF value. This makes the terminal value assumptions (especially the growth rate and ROIC) by far the most impactful inputs — and the most important to get right.",
    answerData: JSON.stringify({ choices: ["Year 1 cash flow", "Years 2–5 cash flows", "Terminal value", "Working capital changes"], correctIndex: 2 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "A firm has EBIT of $100M, tax rate of 25%, D&A of $20M, capex of $40M, and working capital increase of $10M. What is its FCFF?",
    explanation: "FCFF = EBIT(1−t) + D&A − CapEx − ΔWC = 100×0.75 + 20 − 40 − 10 = 75 + 20 − 40 − 10 = $45M.",
    answerData: JSON.stringify({ choices: ["$35M", "$45M", "$55M", "$75M"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "In a DCF, double-counting risk means:",
    explanation: "Double-counting occurs when analysts add a risk premium to the discount rate AND simultaneously apply pessimistic (risk-adjusted) cash flows. Since the discount rate already accounts for risk by reducing present value, pessimistic cash flows further penalise the valuation twice for the same risks.",
    answerData: JSON.stringify({ choices: ["Using both equity and debt costs in WACC", "Adding a risk premium to the discount rate and using risk-adjusted (pessimistic) cash flows simultaneously", "Applying two different growth rates in the terminal value", "Using both historical and implied equity risk premiums"], correctIndex: 1 }) },
]

const damCh03: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "In the WACC formula, what weights should be used for equity and debt?",
    explanation: "Market value weights must be used, not book value weights. Book value of equity can be far below market value (especially for profitable firms), and book value of debt may diverge from market value when credit spreads change. Using book weights distorts the blended cost of capital.",
    answerData: JSON.stringify({ choices: ["Book value weights from the balance sheet", "Market value weights", "Equal weights (50/50)", "Regulatory capital weights"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "Beta in the CAPM measures:",
    explanation: "Beta measures the sensitivity of a stock's return to the market return — its systematic (non-diversifiable) risk. A beta of 1.5 means the stock moves 1.5% for every 1% market move on average. Only systematic risk is priced in the CAPM; idiosyncratic risk is diversified away.",
    answerData: JSON.stringify({ choices: ["Total volatility of the stock's returns", "The stock's sensitivity to market movements (systematic risk)", "The probability that the stock underperforms the market", "The default probability of the firm's debt"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "MEDIUM",
    stem: "The after-tax cost of debt in WACC equals the pre-tax yield on debt multiplied by (1 − tax rate).",
    explanation: "True. Interest payments are tax-deductible, so the effective cost to the firm is the pre-tax yield × (1 − t). For example, a firm with a 6% bond yield and 25% tax rate has an after-tax cost of debt of 4.5%.",
    answerData: JSON.stringify({ correct: true }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "To estimate beta for a private company, the most appropriate approach is:",
    explanation: "Private companies have no stock price to regress. The standard approach is to find public comparable companies ('pure plays'), unlever their betas (remove their capital structure effects), average the unlevered betas, then relever using the target firm's capital structure. This is sometimes called the Hamada or Damodaran approach.",
    answerData: JSON.stringify({ choices: ["Use beta = 1.0 as a default", "Regress accounting returns against market returns", "Use comparable public companies' betas, unlevered and re-levered for the target's capital structure", "Use the bond yield spread as a proxy for beta"], correctIndex: 2 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "A firm has an equity beta of 1.4, D/E ratio of 0.5, and tax rate of 30%. What is the unlevered (asset) beta?",
    explanation: "Unlevered beta = Levered beta / [1 + (1−t)(D/E)] = 1.4 / [1 + 0.7×0.5] = 1.4 / 1.35 ≈ 1.04. Unlevering removes the financial risk from the observed equity beta, leaving only business (operating) risk.",
    answerData: JSON.stringify({ choices: ["0.93", "1.04", "1.19", "1.40"], correctIndex: 1 }) },
]

const damCh04: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "The implied ERP is estimated by:",
    explanation: "The implied ERP backs out the discount rate that makes today's index value equal to the present value of expected future dividends and buybacks, then subtracts the risk-free rate. Unlike historical ERP, it is forward-looking and changes daily with market prices.",
    answerData: JSON.stringify({ choices: ["Averaging historical equity returns over the past 10 years", "Solving for the discount rate that equates current index prices to expected future cash flows, then subtracting the risk-free rate", "Surveying institutional investors about expected market returns", "Using the CAPM beta of the market (which equals 1.0)"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "MEDIUM",
    stem: "The historical equity risk premium is a reliable estimate of the future ERP because it is based on a large sample of data.",
    explanation: "False. Even with long historical samples, the standard error around a historical ERP estimate is large (±2% or more for 50 years of data). Moreover, historical returns reflect not just compensation for risk but also changes in valuations — and past conditions may not represent the future risk-return environment.",
    answerData: JSON.stringify({ correct: false }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "Country risk premiums for emerging markets are added to the base ERP because:",
    explanation: "Investing in emerging markets exposes investors to additional risks — political instability, currency risk, weaker legal protection, less liquid markets, and greater economic volatility — that are not present in developed markets. A CRP compensates investors for bearing these incremental risks.",
    answerData: JSON.stringify({ choices: ["Emerging market companies always have higher betas", "Investors face additional political, currency, and market risks not present in developed markets", "Emerging market risk-free rates are always above developed market rates", "Tax rates are higher in emerging markets"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "If the S&P 500 is trading at 4,500 with expected dividends + buybacks of $180 in year 1 growing at 6% to year 5, then at 3% in perpetuity, and the 10-year Treasury yield is 4.5%, what does this imply about the ERP?",
    explanation: "The implied return on equities can be estimated from these inputs as approximately 8.0–8.5% (solving the dividend discount model for r). Subtracting the 4.5% risk-free rate gives an implied ERP of approximately 3.5–4.0%. This is a typical US implied ERP in a moderate-rate environment.",
    answerData: JSON.stringify({ choices: ["About 1.5%", "About 3.5–4.0%", "About 6.0%", "About 8.5%"], correctIndex: 1 }) },
]

const damCh05: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "The EV/EBITDA multiple is preferred over P/E in many M&A and leveraged buyout analyses because:",
    explanation: "EV/EBITDA is capital-structure neutral — it can be compared across companies with different leverage levels. P/E is affected by debt (interest expense reduces net income), making comparisons between levered and unlevered firms misleading.",
    answerData: JSON.stringify({ choices: ["EBITDA is always positive while earnings can be negative", "EV/EBITDA is capital-structure neutral, enabling comparison across firms with different leverage", "It includes depreciation which P/E ignores", "EV/EBITDA predicts stock returns more accurately"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "The key risk in relative valuation is that:",
    explanation: "If the entire market or sector is overvalued, all comparables will also be overvalued. A stock can look 'cheap' on multiples vs peers while still being expensive in absolute (DCF) terms. Relative valuation tells you where you stand versus the crowd, not whether the crowd is right.",
    answerData: JSON.stringify({ choices: ["Multiples change too frequently to be useful", "Market-wide overvaluation means a 'cheap' stock on multiples may still be expensive in absolute terms", "Only P/E and P/B multiples are statistically valid", "Relative valuation always overestimates growth firms"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "MEDIUM",
    stem: "For a firm earning exactly its cost of equity, the Price/Book ratio should equal 1.",
    explanation: "True. P/B = (ROE − g) / (ke − g). If ROE = ke (the firm earns exactly its cost of equity), then P/B = (ke − g) / (ke − g) = 1. The stock should trade at book value — it is neither value-creating nor value-destroying.",
    answerData: JSON.stringify({ correct: true }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "Two firms in the same sector have identical P/E ratios of 20x. Firm A grows at 20% and Firm B grows at 5%. Which is likely undervalued?",
    explanation: "At the same P/E, Firm A's higher growth means more future earnings per dollar paid today — it is trading at a lower PEG ratio (P/E ÷ growth). PEG for A = 20/20 = 1.0; PEG for B = 20/5 = 4.0. Firm A is likely undervalued relative to its growth prospects.",
    answerData: JSON.stringify({ choices: ["Firm B, because slow growth implies more stable earnings", "Neither — they have the same P/E so they are equally valued", "Firm A, because its lower PEG ratio implies more growth per dollar paid", "Firm B, because P/E should be compared to interest rates, not growth"], correctIndex: 2 }) },
]

const damCh06: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "The fundamental growth equation in Damodaran's framework states that g =",
    explanation: "g = Reinvestment Rate × Return on Capital. A firm grows by deploying capital into the business at a positive return. Growth without reinvestment is unsustainable. This equation is the foundation for internally consistent DCF models.",
    answerData: JSON.stringify({ choices: ["Revenue growth × profit margin", "Reinvestment rate × return on capital", "Dividend payout ratio × earnings growth", "Beta × equity risk premium"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "MEDIUM",
    stem: "Growth always creates value in a DCF model.",
    explanation: "False. Growth creates value only when ROIC > WACC. If a firm reinvests capital at returns below its cost of capital, it destroys value even as it grows. This is why high-growth firms with poor unit economics can be worth less than no-growth firms with high returns.",
    answerData: JSON.stringify({ correct: false }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "A firm earns ROIC of 12% and has a WACC of 12%. Its reinvestment rate is 50%. What is its expected growth?",
    explanation: "g = Reinvestment Rate × ROIC = 50% × 12% = 6%. Importantly, since ROIC = WACC, this growth creates NO additional value — the firm is investing at exactly the cost of capital. The present value of future growth opportunities is zero.",
    answerData: JSON.stringify({ choices: ["0% — the firm should not reinvest", "6% — but this creates no additional value since ROIC = WACC", "12% — equal to the ROIC", "24% — double the reinvestment rate"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "The competitive advantage period (CAP) in valuation refers to:",
    explanation: "The competitive advantage period is the length of time a firm can sustain returns above its cost of capital before competition erodes them back to WACC. Longer CAPs justify higher valuation multiples. Estimating the CAP is essentially asking: how durable is this company's competitive moat?",
    answerData: JSON.stringify({ choices: ["The number of years until a patent expires", "The period during which a firm can sustain ROIC above WACC before competition erodes excess returns", "The time until a firm can access equity markets", "The period covered by the explicit DCF forecast"], correctIndex: 1 }) },
]

export const damodaranQuestionsBySlug: Record<string, typeof damCh01> = {
  "ch01-intro-valuation": damCh01,
  "ch02-dcf-valuation": damCh02,
  "ch03-cost-of-capital": damCh03,
  "ch04-equity-risk-premium": damCh04,
  "ch05-relative-valuation": damCh05,
  "ch06-growth-reinvestment": damCh06,
}
