// Wilmott "Paul Wilmott Introduces Quantitative Finance" — questions by chapter slug

const base = { isActive: true, tags: "[]", sourceRef: null }

const wilCh01: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "In Geometric Brownian Motion, dS = μS dt + σS dW. The term σS dW represents:",
    explanation: "σS dW is the stochastic (random) component of the stock price change. σ is the volatility (annualised), S is the current price, and dW is an increment of a Wiener process — a normally distributed random shock with zero mean and variance dt.",
    answerData: JSON.stringify({ choices: ["The drift (expected return) component", "The random (volatility) component of price change", "The dividend adjustment", "The risk-free rate contribution"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "Under GBM, log-returns ln(S_{t+Δt}/S_t) have mean:",
    explanation: "Under GBM, log-returns are normally distributed with mean (μ − σ²/2)Δt. The σ²/2 correction is the Itô term arising from Jensen's inequality applied to the log function. It is often called the 'Itô correction' or 'volatility drag'.",
    answerData: JSON.stringify({ choices: ["μΔt", "(μ − σ²/2)Δt", "(μ + σ²/2)Δt", "σ²Δt"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "MEDIUM",
    stem: "The variance of a Brownian motion path over time T grows proportionally to T (not T²).",
    explanation: "True. Var(W_T) = T (not T²). Standard deviation grows as √T. This is the key property of diffusion processes and explains why option prices scale with √T, and why VaR scales with √T under the i.i.d. normal assumption.",
    answerData: JSON.stringify({ correct: true }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "Itô's lemma adds an extra term to the ordinary chain rule because:",
    explanation: "In stochastic calculus, (dW)² = dt (not zero as in ordinary calculus where (dt)² → 0). Since dW ~ √dt, the second-order term in the Taylor expansion contributes at order dt and cannot be ignored. This is the fundamental difference between Itô calculus and ordinary calculus.",
    answerData: JSON.stringify({ choices: ["Stochastic processes are not differentiable in the classical sense", "(dW)² = dt rather than 0, making the second-order term non-negligible", "The drift term μ is random", "Log-returns are fat-tailed in practice"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "If a stock follows GBM with μ=10% and σ=20%, what is the expected value of S_T (not the log)?",
    explanation: "E[S_T] = S_0 × e^(μT), not S_0 × e^((μ−σ²/2)T). The log-return has mean (μ−σ²/2)T, but the stock price level has expected value S_0 e^(μT). The (μ−σ²/2) only applies to the log of the price, not the price itself.",
    answerData: JSON.stringify({ choices: ["S_0 × e^((μ−σ²/2)T)", "S_0 × e^(μT)", "S_0 × (1 + μT)", "S_0 × e^(σ√T)"], correctIndex: 1 }) },
]

const wilCh02: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "The key insight of the Black-Scholes-Merton derivation is that by choosing Δ = ∂V/∂S:",
    explanation: "Choosing delta = ∂V/∂S (the hedge ratio) eliminates the stochastic dW term from the hedged portfolio. The resulting portfolio is instantaneously risk-free and must therefore earn the risk-free rate — this no-arbitrage condition gives the BSM PDE.",
    answerData: JSON.stringify({ choices: ["The portfolio earns the expected return μ", "The random component is eliminated, making the portfolio instantaneously risk-free", "Volatility cancels out of the pricing formula", "The option price equals the stock price"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "In the BSM formula for a European call, N(d₂) represents:",
    explanation: "N(d₂) is the risk-neutral probability that the option expires in-the-money (S_T > K). N(d₁) is the delta — the hedge ratio. The formula C = S·N(d₁) − K·e^(−rT)·N(d₂) can be read as: the present value received from the stock (conditional on exercise) minus the present value of paying the strike.",
    answerData: JSON.stringify({ choices: ["The delta of the call option", "The risk-neutral probability that the option expires in-the-money", "The probability of default of the underlying", "The Sharpe ratio of the hedged portfolio"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "EASY",
    stem: "The BSM formula for a European call option depends on the expected return μ of the stock.",
    explanation: "False. Through the delta-hedging argument, μ is replaced by the risk-free rate r in the pricing PDE. The expected return drops out entirely. This is the power of no-arbitrage pricing: option prices are determined by r, σ, S, K, T — not μ.",
    answerData: JSON.stringify({ correct: false }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "Which BSM assumption is most directly violated by the existence of the volatility smile?",
    explanation: "The volatility smile shows that implied vol varies with strike — OTM options trade at different implied vols than ATM options. This directly violates the BSM assumption of constant volatility. If BSM were correct, all options on the same underlying with the same expiry would have the same implied vol.",
    answerData: JSON.stringify({ choices: ["No dividends on the underlying", "Constant risk-free rate", "Constant volatility (σ is the same for all strikes)", "Continuous trading with no transaction costs"], correctIndex: 2 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "The BSM PDE applies to any derivative on a stock following GBM because:",
    explanation: "The delta-hedging argument eliminates the stochastic term for ANY derivative payoff — not just European calls. The resulting PDE is the same regardless of the payoff. Different derivatives are priced by applying different boundary conditions (terminal payoff) to the same PDE.",
    answerData: JSON.stringify({ choices: ["All options have the same delta", "The delta-hedging argument applies to any derivative payoff; only boundary conditions differ", "The PDE is linear so all solutions are superpositions of calls and puts", "Transaction costs are the same for all derivatives"], correctIndex: 1 }) },
]

const wilCh03: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "The delta of a European call option is equal to:",
    explanation: "Call delta = N(d₁), which ranges between 0 and 1. It is the slope of the option price with respect to the stock price — equivalently, the number of shares needed to delta-hedge one long call. Deep ITM calls have delta near 1; deep OTM calls have delta near 0.",
    answerData: JSON.stringify({ choices: ["N(d₂)", "N(d₁)", "e^(−rT)N(d₂)", "1 − N(d₁)"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "EASY",
    stem: "Gamma is always positive for long option positions (calls and puts).",
    explanation: "True. Gamma = ∂²V/∂S² is always positive for long options. A long option always benefits from large moves (in either direction) relative to a delta-hedged position — this positive curvature is always good for the option holder.",
    answerData: JSON.stringify({ correct: true }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "An option position that is 'long gamma, short theta' means:",
    explanation: "Long gamma means the position benefits from large moves in the underlying (positive curvature). Short theta means it loses value each day through time decay. These are two sides of the same coin for long option positions: you pay daily theta for the right to benefit from large moves.",
    answerData: JSON.stringify({ choices: ["The portfolio is delta-neutral but exposed to skew risk", "The position benefits from large moves but loses value each day through time decay", "Gamma gains exceed theta costs regardless of volatility", "The trader is long vega but short the underlying"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "Vega of an at-the-money call option is highest when:",
    explanation: "ATM options have the highest vega for a given time-to-expiry. And for a given strike, vega increases with time to expiry — there is more time for volatility to impact the outcome. So the highest vega belongs to long-dated ATM options.",
    answerData: JSON.stringify({ choices: ["The option is deep in-the-money with short time to expiry", "The option is at-the-money with long time to expiry", "The option is deep out-of-the-money", "The risk-free rate is high"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "For a delta-hedged at-the-money call near expiry, the approximate relationship between theta and gamma is:",
    explanation: "From the BSM PDE (simplified for zero rates, ATM): Θ ≈ −½σ²S²Γ. Theta is approximately minus one half times variance times gamma. This shows directly that gamma and theta trade off: higher gamma means more negative theta — you pay more daily decay for the same curvature benefit.",
    answerData: JSON.stringify({ choices: ["Θ ≈ +½σ²S²Γ (theta and gamma have the same sign)", "Θ ≈ −½σ²S²Γ (theta and gamma have opposite signs)", "Theta equals gamma when the option is ATM", "There is no systematic relationship between theta and gamma"], correctIndex: 1 }) },
]

const wilCh04: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "A delta-hedged long call position profits when:",
    explanation: "The P&L of a delta-hedged long option over interval δt ≈ ½Γ(δS)² − Θδt. This is positive when realized volatility exceeds implied volatility (gamma gains > theta cost). Trading implied vs realized vol is the essence of options market-making.",
    answerData: JSON.stringify({ choices: ["The stock price rises", "Realized volatility exceeds implied volatility", "The stock price falls", "The risk-free rate rises"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "MEDIUM",
    stem: "More frequent delta rebalancing always reduces the risk of a delta-hedged options position.",
    explanation: "False. More frequent rebalancing reduces hedging error from gamma exposure, but increases transaction costs. For large positions, transaction costs can exceed the hedging benefit. Optimal rebalancing involves a tolerance band — only rebalance when delta moves outside a pre-specified range.",
    answerData: JSON.stringify({ correct: false }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "An options trader is long implied vol (long vega). This position profits when:",
    explanation: "Being long vega means the position gains when implied volatility rises. This is typical for long option positions — if you bought an option at IV = 20% and IV rises to 25%, the option becomes more valuable even if the underlying doesn't move.",
    answerData: JSON.stringify({ choices: ["The underlying rises in price", "Implied volatility rises after the position is entered", "Time passes with no movement in the underlying", "Realized volatility is lower than implied volatility"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "The gamma P&L for a delta-hedged call when the stock moves δS is approximately:",
    explanation: "From the Taylor expansion of option price: gamma P&L ≈ ½Γ(δS)². This is always positive for a long gamma position — large moves always help, regardless of direction. The theta cost is approximately ΘδT per unit time. Net P&L = ½Γ(δS)² − ΘδT.",
    answerData: JSON.stringify({ choices: ["Γ × δS (linear in the move)", "½Γ(δS)² (quadratic in the move)", "−Γ × δS (negative linear)", "Γ × (δS)³/6 (cubic in the move)"], correctIndex: 1 }) },
]

const wilCh05: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "The volatility smile refers to the pattern where:",
    explanation: "The volatility smile is the empirical observation that implied volatility varies with strike — it is not flat as BSM assumes. In equity markets, OTM puts have higher implied vol than ATM (skew/smirk). In FX markets, both OTM calls and puts trade at higher IV than ATM (symmetric smile).",
    answerData: JSON.stringify({ choices: ["Implied volatility is higher for longer-dated options", "Implied volatility varies with strike, violating the BSM constant-vol assumption", "Realized volatility exceeds implied volatility on average", "Volatility reverts to its long-run mean over time"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "In equity markets, OTM puts typically trade at higher implied volatility than ATM options because:",
    explanation: "Two reasons drive the equity vol skew: (1) fat left tails — equity returns have larger downside crashes than the lognormal model implies; (2) demand imbalance — portfolio managers buy OTM puts as tail risk insurance, driving up their prices and implied vols.",
    answerData: JSON.stringify({ choices: ["OTM puts have higher delta and therefore higher vega", "Crash risk and demand for downside protection push OTM put prices above lognormal predictions", "OTM puts have longer effective duration than ATM options", "Market makers charge a premium for hedging OTM puts"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "MEDIUM",
    stem: "The local volatility model (Dupire) exactly fits any observed volatility surface by construction.",
    explanation: "True. Dupire's local volatility model σ(S,t) is calibrated to exactly match all observed market option prices across all strikes and maturities. It is the unique diffusion model consistent with a given volatility surface, but it predicts flat forward vol smiles which may not match the dynamics of the smile.",
    answerData: JSON.stringify({ correct: true }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "The SABR model is particularly popular in interest rate options markets because:",
    explanation: "SABR provides a closed-form approximation for implied volatility as a function of strike and time, allowing rapid calibration to market prices. Its parameters (α, β, ρ, ν) have intuitive interpretations, and it naturally generates realistic vol smiles for caplets/floorlets and swaptions.",
    answerData: JSON.stringify({ choices: ["It assumes constant volatility which simplifies hedging", "It provides a tractable implied vol formula that fits market smiles for interest rate options", "It is the only model that satisfies the BSM PDE exactly", "It eliminates the need for delta hedging in fixed income"], correctIndex: 1 }) },
]

const wilCh06: Omit<any, "chapterId">[] = [
  { ...base, questionType: "MCQ", difficulty: "EASY",
    stem: "In Monte Carlo pricing of a European option, each simulated path contributes:",
    explanation: "Each Monte Carlo path simulates a terminal stock price S_T under the risk-neutral measure. The option payoff (e.g., max(S_T−K, 0) for a call) is computed for each path, discounted at the risk-free rate, and averaged over all paths to estimate the option price.",
    answerData: JSON.stringify({ choices: ["One estimate of the stock's expected return", "One discounted payoff; the option price is the average over all paths", "One volatility estimate used to improve the next simulation", "One delta estimate for the hedge ratio"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "MEDIUM",
    stem: "The Crank-Nicolson finite difference scheme is preferred over the explicit scheme because:",
    explanation: "The explicit scheme is conditionally stable — it requires very small time steps relative to grid spacing, or oscillations appear. The Crank-Nicolson scheme (average of explicit and fully implicit) is unconditionally stable and second-order accurate in both Δt and ΔS, making it far more efficient.",
    answerData: JSON.stringify({ choices: ["It requires no boundary conditions at expiry", "It is unconditionally stable and second-order accurate, unlike the explicit scheme", "It does not require solving a matrix system", "It produces exact BSM prices with just two time steps"], correctIndex: 1 }) },
  { ...base, questionType: "TRUE_FALSE", difficulty: "MEDIUM",
    stem: "Monte Carlo simulation is better suited than finite differences for pricing American options.",
    explanation: "False. American options require evaluating early exercise at each point in time — natural for finite differences (just take max(intrinsic, continuation) at each grid node) but difficult for Monte Carlo (requires backward induction, e.g., the Longstaff-Schwartz regression method). Standard Monte Carlo is primarily suited for European and path-dependent options.",
    answerData: JSON.stringify({ correct: false }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "Antithetic variates in Monte Carlo simulation reduces variance by:",
    explanation: "For each random path using a draw Z ~ N(0,1), the antithetic method also simulates the paired path using −Z. Since payoffs from Z and −Z are negatively correlated, averaging them produces an estimate with lower variance than using two independent draws. It roughly halves the number of simulations needed for a given accuracy.",
    answerData: JSON.stringify({ choices: ["Reusing the same random numbers across multiple option payoffs", "For each random draw Z, also simulating the paired path with −Z to reduce variance via negative correlation", "Replacing all normal draws with uniform random variables", "Increasing the number of time steps in each simulation"], correctIndex: 1 }) },
  { ...base, questionType: "MCQ", difficulty: "HARD",
    stem: "In finite difference pricing of an American put, the condition at each grid node is:",
    explanation: "At each node of the FD grid, the American option value is the maximum of the continuation value (holding) and the intrinsic value (immediate exercise: K − S for a put). This ensures the early exercise premium is captured — the American option is always worth at least its intrinsic value.",
    answerData: JSON.stringify({ choices: ["V = 0 (no exercise allowed until expiry)", "V = max(continuation value, intrinsic value)", "V = continuation value + early exercise premium", "V = intrinsic value only (always optimal to exercise)"], correctIndex: 1 }) },
]

export const wilmottQuestionsBySlug: Record<string, typeof wilCh01> = {
  "ch01-random-walk": wilCh01,
  "ch02-bsm-equation": wilCh02,
  "ch03-greeks": wilCh03,
  "ch04-delta-hedging": wilCh04,
  "ch05-volatility-surface": wilCh05,
  "ch06-numerical-methods": wilCh06,
}
