// Hull "Risk Management and Financial Institutions" — questions by chapter slug

const base = { isActive: true, tags: "[]", sourceRef: null }

const hullRiskCh01: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "Which of the following is an example of operational risk?",
    explanation: "Operational risk is defined as losses from failed processes, systems, people, or external events. A rogue trader exploiting control weaknesses is a textbook operational risk event. Market and credit risk events are separate categories.",
    answerData: JSON.stringify({ choices: ["A bond portfolio loses value when interest rates rise", "A counterparty fails to repay a loan", "A rogue trader bypasses internal controls causing a large loss", "A bank's funding costs increase in a crisis"], correctIndex: 2 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "RAROC stands for:",
    explanation: "RAROC (Risk-Adjusted Return on Capital) is computed as risk-adjusted revenue divided by economic capital. It allows comparison of profitability across business lines with different risk profiles — a line generating 20% RAROC is more efficient than one generating 10% RAROC.",
    answerData: JSON.stringify({ choices: ["Risk-Adjusted Rate of Capital", "Risk-Adjusted Return on Capital", "Regulatory Allocation of Risk Capital", "Return Adjusted for Regulatory Cost"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "Systematic risk can be eliminated through diversification in a large portfolio.",
    explanation: "False. Idiosyncratic (firm-specific) risk can be diversified away. Systematic risk — correlated with the broad market — cannot. Investors demand a risk premium only for bearing systematic risk, which is why the CAPM beta is the relevant measure, not total volatility.",
    answerData: JSON.stringify({ correct: false }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "Economic capital is best described as:",
    explanation: "Economic capital is the amount of equity a firm needs to hold to remain solvent at a given confidence level (e.g., 99.9%) over a given horizon (e.g., 1 year). It differs from regulatory capital, which follows prescribed formulae regardless of actual risk.",
    answerData: JSON.stringify({ choices: ["The minimum capital required by bank regulators under Basel III", "The equity a firm needs to stay solvent at a given confidence level over a given horizon", "The book value of equity on the balance sheet", "The market capitalization of the bank"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "A bank runs a trading desk with expected annual return of $20M and economic capital of $100M. What is its RAROC?",
    explanation: "RAROC = Risk-Adjusted Revenue / Economic Capital = $20M / $100M = 20%. The bank would compare this to its hurdle rate (e.g., 15%) to decide whether the desk adds shareholder value.",
    answerData: JSON.stringify({ choices: ["5%", "10%", "20%", "80%"], correctIndex: 2 }),
  },
]

const hullRiskCh02: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "The 1-day 99% VaR of $10M means:",
    explanation: "VaR is a threshold loss: there is a 1% chance (100% − 99%) of losing more than $10M over the next trading day. Equivalently, 99% of the time the loss is expected to be less than $10M.",
    answerData: JSON.stringify({ choices: ["The bank expects to lose exactly $10M tomorrow", "There is a 1% chance of losing more than $10M in one day", "The bank will definitely lose $10M in 100 days", "The average loss in the worst 1% of days is $10M"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "Historical simulation for VaR uses:",
    explanation: "Historical simulation replays the actual observed changes in risk factors over a historical window (e.g., 500 days). It is non-parametric — no distribution is assumed — and naturally captures fat tails, skewness, and correlations as they appeared historically.",
    answerData: JSON.stringify({ choices: ["Monte Carlo scenarios generated from fitted parametric distributions", "The actual observed risk factor changes over a historical window", "A normal distribution with sample mean and variance", "Stress scenarios specified by regulators"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "VaR is a sub-additive risk measure: the VaR of a combined portfolio is always less than or equal to the sum of individual VaRs.",
    explanation: "False. VaR is NOT sub-additive in general. For non-normal distributions, the VaR of a combined portfolio can exceed the sum of individual VaRs — violating the principle that diversification should never increase risk. This is one of VaR's key weaknesses.",
    answerData: JSON.stringify({ correct: false }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "The variance-covariance (model-building) approach to VaR assumes:",
    explanation: "The model-building approach assumes portfolio returns are normally distributed. Under normality, VaR = σ × zα × √Δt. This is fast and analytically tractable but fails when returns are fat-tailed, skewed, or when the portfolio contains options.",
    answerData: JSON.stringify({ choices: ["Returns follow a t-distribution with estimated degrees of freedom", "Portfolio returns are normally distributed", "All positions are in linear instruments with no optionality", "Historical return data is the only valid input"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "A portfolio has daily volatility of $500,000. Using the model-building approach at 99% confidence (z=2.326), what is the 10-day VaR?",
    explanation: "1-day VaR = 2.326 × $500,000 = $1,163,000. 10-day VaR = $1,163,000 × √10 ≈ $3,677,000. The √T scaling assumes i.i.d. normally distributed daily P&Ls.",
    answerData: JSON.stringify({ choices: ["$1,163,000", "$2,326,000", "$3,677,000", "$11,630,000"], correctIndex: 2 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "A key limitation of VaR is that it provides no information about:",
    explanation: "VaR only tells you the loss threshold at a given confidence level. Two portfolios can have identical VaRs but very different tail behaviour — one might have a worst-case loss of $12M and another $500M. VaR says nothing about the severity of losses beyond the threshold.",
    answerData: JSON.stringify({ choices: ["The confidence level used in the calculation", "The losses beyond the VaR threshold (tail loss severity)", "Whether the portfolio is long or short risk", "The time horizon of the risk measurement"], correctIndex: 1 }),
  },
]

const hullRiskCh03: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "Expected Shortfall (ES) is defined as:",
    explanation: "ES (also called CVaR or ETL) is the expected (average) loss conditional on the loss exceeding the VaR threshold. It quantifies the average severity of tail losses, addressing VaR's key weakness of ignoring what happens beyond the threshold.",
    answerData: JSON.stringify({ choices: ["The maximum possible loss under any scenario", "The average loss in scenarios where losses exceed the VaR", "The median loss in the worst 5% of scenarios", "The standard deviation of losses in the tail"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "Which property does VaR violate that makes Expected Shortfall preferable as a risk measure?",
    explanation: "VaR fails sub-additivity — the VaR of a combined portfolio can exceed the sum of individual VaRs, implying that merging positions could appear to increase risk. ES is sub-additive and satisfies all four coherence axioms (monotonicity, translation invariance, positive homogeneity, sub-additivity).",
    answerData: JSON.stringify({ choices: ["Monotonicity", "Translation invariance", "Sub-additivity", "Positive homogeneity"], correctIndex: 2 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "Expected Shortfall is easier to backtest than VaR because more observations are available in the tail.",
    explanation: "False. ES is harder to backtest. By definition, the tail contains few observations (only 1% or 2.5% of days exceed the VaR). Backtesting VaR simply counts exceedances; for ES you need to assess whether the average of the exceedances matches the model. This is statistically much harder with limited tail data.",
    answerData: JSON.stringify({ correct: false }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "The FRTB (Fundamental Review of the Trading Book) replaced 99% VaR with:",
    explanation: "FRTB shifted the primary market risk capital metric from 99% VaR (10-day) to 97.5% ES. At the normal distribution, 99% VaR ≈ 97.5% ES in magnitude, but ES provides information about the shape of the tail beyond the threshold.",
    answerData: JSON.stringify({ choices: ["99.9% VaR", "97.5% Expected Shortfall", "95% Historical Simulation VaR", "99% Stressed CVaR"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "Sub-additivity means that for any two portfolios A and B:",
    explanation: "Sub-additivity: ρ(A+B) ≤ ρ(A) + ρ(B). Economically, this formalizes the diversification principle — combining positions should never result in more risk than the sum of parts. It also means that a firm cannot reduce its capital requirement simply by splitting into subsidiaries.",
    answerData: JSON.stringify({ choices: ["ρ(A+B) = ρ(A) × ρ(B)", "ρ(A+B) ≤ ρ(A) + ρ(B)", "ρ(A+B) ≥ ρ(A) + ρ(B)", "ρ(A+B) = max(ρ(A), ρ(B))"], correctIndex: 1 }),
  },
]

const hullRiskCh04: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "Expected Loss (EL) in credit risk is calculated as:",
    explanation: "EL = PD × LGD × EAD. PD is the probability of default, LGD is the fraction of the exposure lost given default (1 minus recovery rate), and EAD is the exposure at default. EL is the premium banks charge in loan pricing.",
    answerData: JSON.stringify({ choices: ["PD + LGD + EAD", "PD × LGD × EAD", "PD / LGD × EAD", "max(EAD − Recovery, 0)"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "Risk-neutral default probabilities implied from CDS spreads tend to be higher than historical default probabilities because:",
    explanation: "Risk-neutral probabilities incorporate a risk premium on top of the actuarial expected loss. Investors demand extra compensation for bearing credit risk (uncertainty, illiquidity, systemic correlation), so market-implied probabilities exceed historically observed ones.",
    answerData: JSON.stringify({ choices: ["CDS markets are less efficient than bond markets", "Risk-neutral probabilities embed a risk premium above the actuarial expected loss", "Historical data underestimates true default rates due to selection bias", "CDS spreads include accrued interest, inflating the implied probability"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "In the Merton structural model, a firm's equity is modelled as:",
    explanation: "Merton (1974) showed that equity is equivalent to a call option on firm value with strike equal to the face value of debt. If firm value V > D at maturity, equity holders receive V − D. If V < D, they receive nothing (limited liability) — default occurs.",
    answerData: JSON.stringify({ choices: ["A put option on firm value with strike equal to the debt face value", "A call option on firm value with strike equal to the debt face value", "A forward on the firm's assets maturing at the debt's maturity", "A bond with coupon equal to the expected default loss"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "EASY",
    stem: "A Credit Default Swap (CDS) transfers credit risk from the protection buyer to the protection seller.",
    explanation: "True. The protection buyer pays a periodic spread (the CDS premium) and receives the notional minus recovery if a credit event occurs. The protection seller bears the credit risk in exchange for the periodic income.",
    answerData: JSON.stringify({ correct: true }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "A company's 5-year CDS spread is 200bp. Assuming a recovery rate of 40% and continuous compounding, the approximate risk-neutral default probability per year is:",
    explanation: "The CDS spread ≈ (1 − Recovery) × hazard rate. So: 0.02 = 0.60 × h → h ≈ 3.33% per year. This is the instantaneous risk-neutral default intensity. Over 5 years, the survival probability ≈ e^(−0.0333 × 5) ≈ 81.5%.",
    answerData: JSON.stringify({ choices: ["1.2% per year", "2.0% per year", "3.3% per year", "5.0% per year"], correctIndex: 2 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "The distance to default (DD) in the KMV model measures:",
    explanation: "Distance to default = (Asset value − Default point) / Asset volatility. It expresses how many standard deviations of asset value changes separate the firm from default. A high DD implies low default probability; DD falling toward 0 signals distress.",
    answerData: JSON.stringify({ choices: ["The time remaining before a bond matures", "The number of standard deviations of asset value between the current asset value and the default threshold", "The difference between the CDS spread and the risk-free rate", "The fraction of assets that would be lost in default"], correctIndex: 1 }),
  },
]

const hullRiskCh05: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "Under Basel III, the minimum Common Equity Tier 1 (CET1) ratio is:",
    explanation: "Basel III requires banks to hold at least 4.5% CET1 capital as a percentage of risk-weighted assets. Adding the mandatory 2.5% capital conservation buffer brings the effective minimum to 7% CET1 under normal conditions.",
    answerData: JSON.stringify({ choices: ["2%", "4.5%", "8%", "10.5%"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "The three pillars of Basel II are:",
    explanation: "Basel II is structured around three mutually reinforcing pillars: Pillar 1 (minimum capital requirements for credit, market, and operational risk), Pillar 2 (supervisory review of capital adequacy), and Pillar 3 (market discipline through public disclosure).",
    answerData: JSON.stringify({ choices: ["Credit risk, market risk, and operational risk capital", "Minimum capital requirements, supervisory review, and market discipline (disclosure)", "Internal models, standardized approach, and stress testing", "Leverage ratio, liquidity ratio, and capital ratio"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "Under the Advanced IRB approach in Basel II, banks can use their own internal estimates for PD, LGD, and EAD to compute credit risk capital.",
    explanation: "True. The Advanced Internal Ratings-Based (A-IRB) approach allows banks to internally estimate all three key credit risk parameters (PD, LGD, EAD) subject to supervisory validation. The Foundation IRB allows only PD to be internal, with regulator-specified LGD and EAD.",
    answerData: JSON.stringify({ correct: true }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "The Liquidity Coverage Ratio (LCR) under Basel III requires banks to hold:",
    explanation: "The LCR requires banks to maintain sufficient High Quality Liquid Assets (HQLA — cash, central bank reserves, high-grade government bonds) to cover 30 days of net stressed cash outflows. It was introduced after the 2008 crisis revealed that many banks faced acute short-term funding stress.",
    answerData: JSON.stringify({ choices: ["Enough capital to cover expected losses over 1 year", "Enough HQLA to cover 30 days of net stressed cash outflows", "A leverage ratio of at least 3% of total (non-risk-weighted) exposure", "A stable funding surplus for 1 year of business operations"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "Basel I assigned a risk weight of 100% to corporate loans and 0% to OECD sovereign bonds. The main criticism of this approach was:",
    explanation: "Basel I's crude risk weights failed to distinguish between a AAA-rated corporate and a junk-rated one — both received 100%. Similarly, all OECD sovereigns were 0% regardless of actual creditworthiness (e.g., Greece). This ignored the actual credit quality of borrowers and created regulatory arbitrage opportunities.",
    answerData: JSON.stringify({ choices: ["It was too complex for smaller banks to implement", "Risk weights were too crude, ignoring actual credit quality of individual borrowers", "It required too much capital from investment banks", "It did not include operational risk capital requirements"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "The output floor introduced in Basel IV limits banks' capital savings from internal models by requiring that RWA computed under internal models be at least what percentage of the standardized approach RWA (when fully phased in)?",
    explanation: "Basel IV sets an output floor of 72.5%: a bank's internal model-based RWA cannot be less than 72.5% of the standardized approach RWA. This prevents excessive model-driven capital reduction and creates a backstop against model risk.",
    answerData: JSON.stringify({ choices: ["50%", "60%", "72.5%", "85%"], correctIndex: 2 }),
  },
]

const hullRiskCh06: Omit<any, "chapterId">[] = [
  {
    ...base,
    questionType: "MCQ",
    difficulty: "EASY",
    stem: "The trading book consists of positions that banks hold:",
    explanation: "The trading book contains positions held for trading purposes or to hedge other trading book items — they are mark-to-market daily. The banking book contains positions held to maturity (e.g., traditional loans, held-to-maturity bonds) which are accrual-accounted.",
    answerData: JSON.stringify({ choices: ["In foreign currencies only", "For trading or hedging, marked to market daily", "For long-term investment, accrual-accounted", "On behalf of retail clients in fiduciary capacity"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "In VaR model backtesting, the traffic light approach classifies how many exceptions in 250 trading days as 'red zone' (triggering maximum capital add-on)?",
    explanation: "The traffic light approach: 0–4 exceptions = green (acceptable), 5–9 = yellow (increased scrutiny, multiplier increases), 10+ = red (maximum penalty, multiplier at 4). With a true 99% VaR, 2.5 exceptions are expected over 250 days — red zone implies clear model inadequacy.",
    answerData: JSON.stringify({ choices: ["5 or more", "7 or more", "10 or more", "15 or more"], correctIndex: 2 }),
  },
  {
    ...base,
    questionType: "TRUE_FALSE",
    difficulty: "MEDIUM",
    stem: "Stressed VaR uses a 12-month historical period of financial stress (e.g., 2008) rather than the most recent data.",
    explanation: "True. Stressed VaR was introduced in Basel 2.5 to address the procyclicality of standard VaR — in calm markets, VaR falls and capital falls. By anchoring to a stress period (typically 2007–2008), stressed VaR ensures capital does not shrink to dangerously low levels in benign market conditions.",
    answerData: JSON.stringify({ correct: true }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "MEDIUM",
    stem: "Under FRTB, which new test must trading desks pass to be eligible for the internal models approach?",
    explanation: "FRTB introduces the P&L Attribution (PLA) test, which requires that the P&L explained by the risk model (hypothetical P&L) closely matches the actual daily desk P&L. Desks that fail the PLA test must revert to the standardized approach. This was not required under pre-FRTB rules.",
    answerData: JSON.stringify({ choices: ["Liquidity stress test under LCR scenarios", "P&L Attribution (PLA) test comparing model P&L to actual desk P&L", "VaR backtesting over a 500-day window", "Credit stress test for counterparty exposures"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "FRTB introduces 'liquidity horizons' for different asset classes. The purpose is to:",
    explanation: "FRTB recognises that different instruments take different amounts of time to exit without excessive market impact. Rather than using a uniform 10-day scaling, it applies asset-class-specific horizons (10 to 120 days), making capital more sensitive to actual liquidity risk.",
    answerData: JSON.stringify({ choices: ["Ensure banks hold sufficient HQLA for 30-day stress outflows", "Apply longer holding periods for less liquid instruments, making ES capital more sensitive to liquidity", "Replace VaR backtesting with liquidity stress testing", "Limit the size of individual trading positions as a fraction of daily volume"], correctIndex: 1 }),
  },
  {
    ...base,
    questionType: "MCQ",
    difficulty: "HARD",
    stem: "Basel 2.5 required banks to compute capital as the higher of current VaR and a multiple of the 60-day average VaR. The multiplier starts at 3 and increases when:",
    explanation: "The multiplier increases when backtesting reveals poor model performance — specifically when the number of exceptions in 250 trading days enters the yellow or red zone. This creates an incentive to maintain accurate models: poor performance leads directly to higher capital charges.",
    answerData: JSON.stringify({ choices: ["Market volatility exceeds a threshold set by the regulator", "Backtesting reveals too many exceptions, indicating poor model accuracy", "The bank's CET1 ratio falls below 8%", "The bank switches from historical simulation to Monte Carlo VaR"], correctIndex: 1 }),
  },
]

export const hullRiskQuestionsBySlug: Record<string, typeof hullRiskCh01> = {
  "ch01-risk-introduction": hullRiskCh01,
  "ch02-value-at-risk": hullRiskCh02,
  "ch03-expected-shortfall": hullRiskCh03,
  "ch04-credit-risk": hullRiskCh04,
  "ch05-basel": hullRiskCh05,
  "ch06-market-risk-capital": hullRiskCh06,
}
